run:
  timeout: 5m
  tests: true

linters:
  enable-all: true
  disable:
    # Too strict for this project
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - wsl
    - lll
    - funlen
    - cyclop
    - nestif
    - godox
    - godot
    - gofumpt
    - varnamelen
    - tagliatelle
    # Conflict with other linters
    - gci
    - goimports
    # Not suitable for this project
    - ireturn
    - depguard
    - gosmopolitan
    - mnd
    - nlreturn
    - wrapcheck
    - err113
    - paralleltest
    - thelper
    - testifylint
    - intrange
    - nonamedreturns
    - usetesting
    - unparam
    - interfacebloat
    - dupl
    - maintidx
    - errname
    - tagalign
    - usestdlibvars
    - tenv
    - perfsprint
    - forbidigo
    - forcetypeassert
    - errchkjson
    - gocritic
    - goconst
    - unused
    - errorlint
    - govet
    - nilerr
    - noctx
    - contextcheck
    - testpackage

linters-settings:
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 40
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 5
  misspell:
    locale: US
  govet:
    enable-all: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
    enabled-checks:
      - dupImport
      - ifElseChain
      - nestingReduce
      - paramTypeCombine
      - commentedOutCode
  staticcheck:
    checks:
      - all
  stylecheck:
    checks:
      - all

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl
    - path: cmd/
      linters:
        - errcheck
        - gocognit
        - gocyclo
  max-issues-per-linter: 100
  max-same-issues: 10
